spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgos
    username: root
    password: rhkdgml0421
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace